# Generated by Django 4.2.30 on 2026-04-11 06:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import oj.models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSampleCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('input_file', models.FileField(upload_to=oj.models.sample_input_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['in'])])),
                ('output_file', models.FileField(upload_to=oj.models.sample_output_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['out'])])),
                ('input_text', models.TextField(blank=True, editable=False)),
                ('output_text', models.TextField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_cases', to='oj.problem')),
            ],
            options={
                'ordering': ['problem_id', 'sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='problemsamplecase',
            constraint=models.UniqueConstraint(fields=('problem', 'sort_order'), name='uniq_problem_sample_case_order'),
        ),
    ]
